
# Copyright (c) 2024 Jelmer de Vries
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation in its latest version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIComps/QTGeneration/DataAnalysisWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.list_selector = QtWidgets.QComboBox(self.centralwidget)
        self.list_selector.setObjectName("list_selector")
        self.horizontalLayout_2.addWidget(self.list_selector)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setObjectName("tab_widget")
        self.overview_tab = QtWidgets.QWidget()
        self.overview_tab.setObjectName("overview_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.overview_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.data_ranges_table = QtWidgets.QTableView(self.overview_tab)
        self.data_ranges_table.setObjectName("data_ranges_table")
        self.gridLayout_4.addWidget(self.data_ranges_table, 1, 0, 1, 1)
        self.download_control_layout = QtWidgets.QGridLayout()
        self.download_control_layout.setObjectName("download_control_layout")
        self.download_frame_layout = QtWidgets.QHBoxLayout()
        self.download_frame_layout.setObjectName("download_frame_layout")
        self.label_6 = QtWidgets.QLabel(self.overview_tab)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.download_frame_layout.addWidget(self.label_6)
        self.download_control_layout.addLayout(self.download_frame_layout, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.overview_tab)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.download_control_layout.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.overview_tab)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.download_control_layout.addWidget(self.label_8, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.download_control_layout, 0, 0, 1, 1)
        self.tab_widget.addTab(self.overview_tab, "")
        self.rate_tab = QtWidgets.QWidget()
        self.rate_tab.setObjectName("rate_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.rate_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.data_count_table = QtWidgets.QTableView(self.rate_tab)
        self.data_count_table.setObjectName("data_count_table")
        self.gridLayout_6.addWidget(self.data_count_table, 0, 0, 1, 1)
        self.tab_widget.addTab(self.rate_tab, "")
        self.heatmap_tab = QtWidgets.QWidget()
        self.heatmap_tab.setObjectName("heatmap_tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.heatmap_tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.heatmap_layout = QtWidgets.QGridLayout()
        self.heatmap_layout.setObjectName("heatmap_layout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.heatmap_layout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.heatmap_layout, 0, 0, 1, 1)
        self.tab_widget.addTab(self.heatmap_tab, "")
        self.gridLayout.addWidget(self.tab_widget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Movers"))
        self.label_2.setText(_translate("MainWindow", "List"))
        self.tab_widget.setToolTip(_translate("MainWindow", "<html><head/><body><p>Testing</p></body></html>"))
        self.overview_tab.setAccessibleName(_translate("MainWindow", "Movers"))
        self.label_6.setText(_translate("MainWindow", "Gap up/down"))
        self.label_10.setText(_translate("MainWindow", "Conditions:"))
        self.label_8.setText(_translate("MainWindow", "Available Data:"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.overview_tab), _translate("MainWindow", "Overview"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.rate_tab), _translate("MainWindow", "Rates"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.heatmap_tab), _translate("MainWindow", "Heatmap"))
