
# Copyright (c) 2024 Jelmer de Vries
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation in its latest version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIComps/QTGeneration/StairstepWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.step_table = QtWidgets.QTableWidget(self.tab_3)
        self.step_table.setObjectName("step_table")
        self.step_table.setColumnCount(12)
        self.step_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.step_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.step_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.step_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.step_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.step_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.step_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.step_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.step_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.step_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.step_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.step_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.step_table.setHorizontalHeaderItem(11, item)
        self.gridLayout_3.addWidget(self.step_table, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rsi_table = QtWidgets.QTableWidget(self.tab_4)
        self.rsi_table.setObjectName("rsi_table")
        self.rsi_table.setColumnCount(7)
        self.rsi_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rsi_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rsi_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rsi_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rsi_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.rsi_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.rsi_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.rsi_table.setHorizontalHeaderItem(6, item)
        self.gridLayout_2.addWidget(self.rsi_table, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.list_selector = QtWidgets.QComboBox(self.centralwidget)
        self.list_selector.setObjectName("list_selector")
        self.horizontalLayout_2.addWidget(self.list_selector)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.fetch_button = QtWidgets.QPushButton(self.centralwidget)
        self.fetch_button.setObjectName("fetch_button")
        self.horizontalLayout_2.addWidget(self.fetch_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Momentum"))
        item = self.step_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stock"))
        item = self.step_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Price"))
        item = self.step_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "5m"))
        item = self.step_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "15m"))
        item = self.step_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "1h"))
        item = self.step_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "4h"))
        item = self.step_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "1d"))
        item = self.step_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "5m"))
        item = self.step_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "15m"))
        item = self.step_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "1h"))
        item = self.step_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "4h"))
        item = self.step_table.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "1d"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "StairStep"))
        item = self.rsi_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stock"))
        item = self.rsi_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Price"))
        item = self.rsi_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "5m"))
        item = self.rsi_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "15m"))
        item = self.rsi_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "1h"))
        item = self.rsi_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "4h"))
        item = self.rsi_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "1d"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "RSI"))
        self.label_2.setText(_translate("MainWindow", "List"))
        self.fetch_button.setText(_translate("MainWindow", "Fetch!"))
