# Form implementation generated from reading ui file 'UIComps/QTGeneration/StockListTab.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 443)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stock_table = QtWidgets.QTableView(parent=Form)
        self.stock_table.setObjectName("stock_table")
        self.verticalLayout_2.addWidget(self.stock_table)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.unrealized_pnl_label = QtWidgets.QLabel(parent=Form)
        self.unrealized_pnl_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.unrealized_pnl_label.setObjectName("unrealized_pnl_label")
        self.horizontalLayout_2.addWidget(self.unrealized_pnl_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.total_value_label = QtWidgets.QLabel(parent=Form)
        self.total_value_label.setObjectName("total_value_label")
        self.horizontalLayout_2.addWidget(self.total_value_label, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Unrealized PNL:"))
        self.unrealized_pnl_label.setText(_translate("Form", "0.0"))
        self.label.setText(_translate("Form", "Total Value:"))
        self.total_value_label.setText(_translate("Form", "0.0"))
