
# Copyright (c) 2024 Jelmer de Vries
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation in its latest version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optionsGraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from uiComps.generalUIFunctionality import MyAppWindow
from PyQt5.QtCore import QObject, QEvent
from uiComps.qtGeneration.PositionWindow_UI import Ui_MainWindow as PositionWindow_UI
from dataHandling.Constants import Constants

 
class PositionWindow(MyAppWindow, PositionWindow_UI):

    def __init__(self):
        MyAppWindow.__init__(self)
        PositionWindow_UI.__init__(self)

        self.setupUi(self)
        self.connectActions()


    def connectActions(self):
        self.cancel_all_button.clicked.connect(self.cancelAllTrades)
    
