# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optionsGraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import Qt, pyqtSlot
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QTableWidgetItem
import numpy as np
from uiComps.qtGeneration.BayesianFitting_UI import Ui_MainWindow as BayesianFitting_UI
import sys
from dataHandling.Constants import Constants

#from generalFunctionality.UIFunctions import findRowForValue, AlignDelegate, PercAlignDelegate

from uiComps.customWidgets.PlotWidgets.CandlePlotWidget import CandlePlotWidget


class BayesianFittingWindow(QMainWindow, BayesianFitting_UI): #, SymbolFinderImplementation

    current_selection = None

    def __init__(self):
        QMainWindow.__init__(self)
        BayesianFitting_UI.__init__(self)
        #SymbolFinderImplementation.__init__(self)
        self.setupUi(self)
        
        self.data_plot = CandlePlotWidget()
        self.vertical_stack.insertWidget(1, self.data_plot)
    

        self.connectActions()

        self.stock_list = dict()


    def connectActions(self):
        self.fit_data_button.clicked.connect(self.fitModelToData)
        self.list_selector.currentIndexChanged.connect(self.listSelection)
        self.ticker_selection.currentIndexChanged.connect(self.tickerSelection)

    
    @pyqtSlot(str, dict)
    def apiUpdate(self, signal, sub_signal):
        print(f"TrradingWindow.apiUpdate: {signal}")

