
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optionsGraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QCompleter, QTableWidgetItem
import numpy as np
from dataHandling.Constants import Constants
from .DataDownloaderWindow import DataDownloaderWindow
import sys, threading
import datetime
import pandas as pd
from PyQt5.QtWidgets import QCompleter

from dataHandling.SymbolManager import SymbolDataManager


class DataDownloader(DataDownloaderWindow):

    current_contract = None

    def __init__(self, symbol_manager, history_manager):
        super().__init__()
        self.symbol_manager = symbol_manager
        self.symbol_manager.api_updater.connect(self.apiUpdate, Qt.QueuedConnection)
        self.history_manager = history_manager
        self.history_manager.addNewListener(self, self.apiUpdate)


    def selectedContract(self, contractDetails):
        self.current_contract = contractDetails

    def returnSelection(self):
        pass


    def fetchHistoricalData(self):
        start_date = self.start_date_widget.selectedDate().toPyDate()
        print(f"#####Date type is {type(start_date)}")
        end_date = self.end_date_widget.selectedDate().toPyDate()

        print(type(start_date))
        if self.current_contract is not None:
            self.history_manager.fetchBarsForSpecs(self.current_contract, start_date, end_date, self.bar_combobox.currentText())

    @pyqtSlot(str, dict)
    def apiUpdate(self, signal, sub_signal):
        super().apiUpdate(signal, sub_signal)

        if signal == Constants.HISTORICAL_DATA_FETCH_COMPLETE:
            self.saveData()


    def saveData(self, separately=False):
        print("We save the completed frame")
        self.history_manager.historicalDF.sort_index(inplace=True)
        file_name = './data/downloads/' + self.current_contract.symbol + '_daily.csv'
        self.history_manager.historicalDF.to_csv(file_name)

        #TODO this should be in super
    def accepts(self, value):
        return False

        