# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optionsGraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QMainWindow
from uiComps.qtGeneration.Position_UI import Ui_MainWindow as Position_UI


class OptionPositionWindow(QMainWindow, Position_UI):

    def __init__(self):
        QMainWindow.__init__(self)
        Position_UI.__init__(self)

        self.setupUi(self)


